---
title: "Summary epicurve"
output: html_notebook
---

- Summarise the time span and shape of the data

```{r setup}
library(sf)
library(tidyverse)
library(ggrepel)
library(patchwork)
library(readxl)
library(geodata)
library(rmapshaper)
library(showtext)
showtext_auto()

R_files = list.files("../R/functions", "\\.R$", recursive=TRUE, full.names=TRUE)
for (file in R_files) { source(file) }
```

```{r data}
borders = world(path=tempdir(), resolution = 4) %>%
  st_as_sf() %>%
  rename(name = NAME_0)
level0 = st_read("../data/china/gadm41_CHN_0.json", quiet=TRUE) %>%
  mutate(shapeName = COUNTRY)
level1 = st_read("../data/china/gadm41_CHN_1.json", quiet=TRUE) %>%
  mutate(shapeName = NAME_1, shapeNameCN=NL_NAME_1)
level2 = st_read("../data/china/gadm41_CHN_2.json", quiet=TRUE) %>%
  mutate(shapeName = NAME_2, shapeNameCN = NL_NAME_2)
level3 = st_read("../data/china/gadm41_CHN_3.json", quiet=TRUE) %>%
  mutate(shapeName = NAME_3, shapeNameCN = NL_NAME_3)
# townships = tribble(
#   ~shapeName, ~shapeNameCN, ~x, ~y,
#   "Guantangxiang", "观堂乡", 115.436, 33.7827,
#   "Maoyangzhen", "毛阳镇", 109.5075, 18.9383
# ) %>% st_as_sf(coords=c("x", "y"), crs=4326)
```

```{r process_data}
china = level0

hainan = level1 %>% filter(shapeName == "Hainan")
yunnan = level1 %>% filter(shapeName == "Yunnan")
henan = level1 %>% filter(shapeName == "Henan")

provinces_oi = bind_rows(hainan, yunnan, henan)

wanning = level3 %>% filter(shapeName == "Wanning")
tengchong = level3 %>% filter(shapeName == "Tengchong")
yingjiang = level3 %>% filter(shapeName == "Yingjiang")
huangchuan = level3 %>% filter(shapeName == "Huangchuan")
dengzhou = level3 %>% filter(shapeName == "Deng") %>% mutate(shapeName = "Dengzhou")
xiayi = level3 %>% filter(shapeName == "Xiayi")

# guantang = townships %>% filter(shapeName == "Guantangxiang")
guantang = level3 %>% filter(shapeName == "Luyi") %>% mutate(shapeName = "Guantang")
maoyang = level3 %>% filter(shapeName == "BaotingLi") %>% mutate(shapeName = "Maoyang")

sites = bind_rows(huangchuan, dengzhou, xiayi, guantang, tengchong, yingjiang, maoyang, wanning, hainan) %>%
  dplyr::select(shapeName, shapeProvince=NAME_1, shapeNameCN)
st_write(sites, "../data/china/sites.geojson", delete_dsn=T)

china_bbox = st_bbox(china)
provinces_bbox = st_bbox(provinces_oi)
sites_bbox = st_bbox(sites)
```

```{r aoi}
ggplot() +
  geom_sf(data = borders, color="grey", fill="grey") +
  geom_sf(data = level1, color="white", fill="grey") +
  # geom_sf(data=china, color="black", fill="transparent", linewidth=0.5) +
  geom_sf(data=provinces_oi, fill="#00FFFF", color="#00FFFF", linewidth=1, alpha=0.5) +
  geom_sf_text(data=provinces_oi, aes(label=paste(shapeNameCN, str_remove(shapeName, " Province")))) +
  # geom_shadowtext(data = province_labels, aes(x=x, y=y, label=shapeName)) +
  # geom_text_repel(data = provinces_oi, aes(x=x, y=y, label=shapeName),
  #                 color = "white", bg.color = "black") +
  coord_sf_bbox(china) +
  theme_minimal() +
  labs(x = NULL, y = NULL)

ggsave("plots/china_areas_of_interest.png", width=6, height=4)
```

```{r}
ggplot() +
  geom_sf(data = borders, color="grey", fill="grey") +
  geom_sf(data = level1, color="white", fill="grey") +
  # geom_sf(data=china, color="white", fill="transparent", linewidth=0.5) +
  geom_sf(data=provinces_oi, fill="pink", color="white", alpha=1) +
  geom_sf(data=sites, fill="#00FFFF", color="#00FFFF", linewidth=0.25, alpha=0.5) +
  # geom_sf_text(data=sites %>% distinct(shapeName, .keep_all=T), aes(label=shapeName)) +
  ggrepel::geom_text_repel(
    data = sites %>% distinct(shapeName, .keep_all=T),
    aes(label = shapeName, geometry = geometry),
    size = 12,
    stat = "sf_coordinates"
  ) +
  coord_sf_bbox(provinces_oi, buffer=2e5) +
  theme_minimal() +
  theme(text = element_text(size=24)) +
  labs(x = NULL, y = NULL)

ggsave("../plots/china_sites.png", width=6, height=4, scale=1)
```

```{r}
# Process in order of centroids from north to south
# sites %>%
#   mutate(Longitude = st_coordinates(st_centroid(.))[,1],
#          Latitude = st_coordinates(st_centroid(.))[,2]) %>%
#   arrange(desc(Latitude)) %>%
#   distinct(shapeName, .keep_all=TRUE) %>%
#   mutate(shapeName = shapeName %>% str_remove("(shi|xiang|xian)$")) %>%
#   dplyr::select(shapeName, Longitude, Latitude) %>%
#   st_drop_geometry() %>%
#   as.data.frame() %>%
#   dput()
```

Map of Henan

```{r}
library(maps)
cities_comparison = world.cities %>%
  filter(name %in% c("New York", "London", "Paris", "Miami", "Los Angeles"),
         country.etc %in% c("USA", "UK", "France", "Spain"))
cities_plot = world.cities %>%
  filter(name %in% c("Shanghai", "Beijing")) %>%
  st_as_sf(coords=c("long", "lat"), crs=4326)
map_plot = ggplot() +
  geom_sf(data = borders, color="grey", fill="grey") +
  geom_sf(data = level1, color="white", fill="grey") +
  geom_sf(data=henan, fill="#00FFFF", color="#00FFFF", linewidth=1, alpha=0.5) +
  geom_sf(data=cities_plot, size=0.1) +
  # geom_sf_text(data=cities_plot, aes(label=name)) +
  ggrepel::geom_text_repel(
    data = cities_plot,
    aes(label = name, geometry = geometry),
    stat = "sf_coordinates",
    min.segment.length = 0,
    segment.color = "transparent"
  ) +
  geom_sf_text(data=henan, aes(label=paste(shapeNameCN, str_remove(shapeName, " Province")))) +
  coord_sf_bbox(china) +
  scale_y_continuous(breaks=cities_comparison$lat,
                     labels=cities_comparison$name) +
  theme(panel.background = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank()) +
  labs(x = NULL, y = NULL)
```

```{r}
henan_plot = ggplot() +
  # geom_sf(data = henan, color="grey", fill="grey") +
  geom_sf(data = henan, color="#00FFFF", fill="#00FFFF", linewidth=1, alpha=0.5) +
  geom_sf(data=bind_rows(guantang, dengzhou), fill="#FF00FF", color="#FF00FF", linewidth=1, alpha=0.5) +
  ggrepel::geom_text_repel(
    data = bind_rows(guantang, dengzhou),
    aes(label = shapeName, geometry = geometry),
    # size = 12,
    stat = "sf_coordinates"
  ) +
  geom_sf_text(data=henan, aes(label=paste(shapeNameCN, str_remove(shapeName, " Province")))) +
  theme(panel.background = element_blank(),
        axis.ticks.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank()) +
  labs(x = NULL, y = NULL)
henan_plot
```

```{r}
library(terra)
library(tidyverse)
library(stars)
library(ggrepel)
library(patchwork)
library(memoise)
R_functions = list.files("../R/functions", "\\.R$", recursive=TRUE, full.names=TRUE)
for (file in R_functions) { source(file) }

tavg_dir = "../data/wc2.1_2.5m_tavg"
tmin_dir = "../data/wc2.1_2.5m_tmin"
tmax_dir = "../data/wc2.1_2.5m_tmax"
prec_dir = "../data/wc2.1_2.5m_prec"
# bio_dir = "../data/wc2.1_2.5m_bio"
# bio_names = c("Annual mean temperature", "Mean diurnal range", "Isothermality", "Temperature seasonality", "Max temperature of warmest month", "Min temperature of coldest month", "Temperature annual range", "Mean temperature of wettest quarter", "Mean temperature of driest quarter", "Mean temperature of the warmest quarter", "Mean temperature of the coldest quarter", "Annual precipitation", "Precipitation of wettest month", "Precipitation of driest month", "Precipitation seasonality", "Precipitation of wettest quarter", "Precipitation of driest quarter", "Precipitation of warmest quarter", "Precipitation of coldest quarter")

# tavg = read_worldclim_raster(tavg_dir)
# bio = read_worldclim(bio_dir)

read_worldclim_stars = function(dir) {
  tifs = list.files(dir, "\\.tif$", full.names=T)
  tifs_num = as.integer(str_extract(tifs, "[0-9]+(?=\\.tif$)"))
  raw = do.call(c, lapply(tifs[order(tifs_num)], read_stars))
  names(raw) = names(raw) %>% str_extract("[^_]+_[0-9]+(?=\\.tif$)")
  raw
}
read_worldclim_raster = function(dir) {
  tifs = list.files(dir, "\\.tif$", full.names=T)
  tifs_num = as.integer(str_extract(tifs, "[0-9]+(?=\\.tif$)"))
  raw = raster::stack(tifs[order(tifs_num)])
  names(raw) = names(raw) %>% str_extract("[^_]+_[0-9]+$")
  raw
}
read_worldclim_terra = function(dir) {
  tifs = list.files(dir, "\\.tif$", full.names=T)
  tifs_num = as.integer(str_extract(tifs, "[0-9]+(?=\\.tif$)"))
  raw = terra::rast(tifs[order(tifs_num)])
  names(raw) = names(raw) %>% str_extract("[^_]+_[0-9]+$")
  raw
}


tavg = read_worldclim_raster("../data/wc2.1_30s_tavg_crop")
# tmin = read_worldclim(tmin_dir)
# tmax = read_worldclim(tmax_dir)
prec = read_worldclim_raster(prec_dir)


extract_layers = function(layers, geom, names_to="layer", use_area_weighted_quantiles=TRUE) {
  if (use_area_weighted_quantiles & !"RasterStack" %in% class(layers)) {
    stop("Area-weighted quantiles requires `layers` to be a `RasterStack` object.")
  }
  var_name = names(layers)[1] %>% str_extract("[^_]+(?=_)")
  var_names = paste(var_name, c("mean", "LQ", "UQ"), sep="_")
  
  fns = list(function(x) { mean(x, na.rm=T) },
             function(x) { quantile(x, 0.25, na.rm=T) },
             function(x) { quantile(x, 0.75, na.rm=T) }) %>%
    setNames(var_names)
  if (use_area_weighted_quantiles) {
    # list col version with one value in the vector per cell covered
    raw_values = lapply(fns, function(f) {
      val = raster::extract(layers, geom)
      val[!is.na(val)]
    })
    processed_values = lapply(seq_along(raw_values) %>% setNames(names(raw_values)), function(i) {
      x = raw_values[[i]] %>% setNames(paste0("V", seq_along({.})))
      column = lapply(seq_along(x), function(j) {
        y = x[[j]]
        colnames(y) = seq_len(dim(y)[2])
        v = y %>%
          as_tibble() %>%
          pivot_longer(everything(), names_to=names_to) %>%
          mutate(V = paste0("V", j),
                 !!names_to  := as.numeric(!!rlang::sym(names_to)),
                 .before=1)
      }) %>%
        bind_rows()
    }) %>%
      bind_rows(.id = "var") %>%
      pivot_wider(names_from = var, values_fn = list)
  } else {
    # single value per geometry
    raw_values = lapply(fns, function(f) raster::extract(layers, geom, FUN=f))
    processed_values = lapply(seq_along(raw_values), function(i) {
      x = raw_values[[i]] %>% st_drop_geometry() %>%
        as_tibble() %>%
        select(-geometry) %>%
        t() %>%
        as_tibble() %>%
        mutate(!!names_to := row_number(), .before=1) %>%
        pivot_longer(-!!names_to, names_to="V", values_to=var_names[[i]])
      if (i > 1) {
        x = x %>% select(!!var_names[[i]])
      }
      x
    }) %>%
      bind_cols()
  }
  
  # Add original geometry information
  geom %>%
    st_drop_geometry() %>%
    mutate(V = paste0("V", row_number())) %>%
    right_join(processed_values, by="V") %>%
    dplyr::select(-V) -> xx
}

tavg_sites = extract_layers(tavg, henan, "month")

prec_sites = extract_layers(prec, henan, "month")
```

```{r}
temp_henan = tavg_sites %>%
  mutate(tavg = sapply(tavg_mean, mean)) %>%
  select(month, tavg)
prec_henan = prec_sites %>%
  mutate(prec = sapply(prec_mean, mean)) %>%
  select(month, prec)
scale_prec = max(prec_henan$prec) / max(temp_henan)
clim_henan = full_join(temp_henan, prec_henan, by="month") %>%
  as_tibble() %>%
  mutate(prec = prec / scale_prec) %>%
  rename(Precipitation = prec,
         Temperature = tavg)
clim_plot = clim_henan %>%
  pivot_longer(-month) %>%
  ggplot(aes(x = month, y = value, color = name)) +
  geom_line() +
  scale_x_continuous(breaks = 1:12, labels = sapply(month.abb, function(x) {substr(x,1,1)})) +
  scale_y_continuous(sec.axis = sec_axis(trans = ~.*scale_prec, name="Precipitation (mm)")) +
  scale_color_manual(values = c("Precipitation"="darkblue", "Temperature"="tomato")) +
  labs(color = NULL, x = "Month", y = "Mean temperature (°C)") + 
  theme(legend.position = "none",
        axis.ticks.y.left = element_line(color="tomato"),
        axis.ticks.y.right = element_line(color="darkblue"),
        axis.text.y.left = element_text(color="tomato"),
        axis.text.y.right = element_text(color="darkblue"),
        axis.title.y.left = element_text(color="tomato"),
        axis.title.y.right = element_text(color="darkblue"))
```

```{r}
(map_plot + henan_plot) / clim_plot + plot_layout(heights = c(2, 1))
ggsave("../plots/henan.png", width=8, height=4)
```

Just Guantang and Dengzhou for the second results chapter

```{r}
ggplot() +
  geom_sf(data = borders, color="grey", fill="grey") +
  geom_sf(data = level1, color="white", fill="grey") +
  # geom_sf(data=china, color="white", fill="transparent", linewidth=0.5) +
  geom_sf(data=provinces_oi, fill="pink", color="white", alpha=1) +
  geom_sf(data=sites, fill="#00FFFF", color="#00FFFF", linewidth=0.25, alpha=0.5) +
  # geom_sf_text(data=sites %>% distinct(shapeName, .keep_all=T), aes(label=shapeName)) +
  ggrepel::geom_text_repel(
    data = sites %>% distinct(shapeName, .keep_all=T),
    aes(label = shapeName, geometry = geometry),
    size = 12,
    stat = "sf_coordinates"
  ) +
  coord_sf_bbox(provinces_oi, buffer=2e5) +
  theme_minimal() +
  theme(text = element_text(size=24)) +
  labs(x = NULL, y = NULL)

ggsave("../plots/china_sites.png", width=6, height=4, scale=1)
```