---
title: "Relapse duration"
output: html_notebook
---

Investigate what ODE structure would be required for a delayed relapse.

```{r setup}
library(tidyverse)
library(readxl)
```

```{r}
relapse = read_excel("../data/china/Guantang Relapse Data - GJY.xlsx", "Relapse", skip=1) %>%
  mutate_all(as.character) %>%
  pivot_longer(cols=matches("relapse"), names_to="event", values_to="delay") %>%
  mutate(delay = as.numeric(delay))

ggplot(relapse, aes(x=delay, fill=event)) +
  geom_histogram(binwidth=30) +
  facet_wrap(vars(event), ncol=1)

sample_1st = relapse %>%
  filter(event == "1st relapse",
         delay > 100) %>%
  pull(delay)
sample_mean = mean(sample_1st)
sample_var = var(sample_1st)

```

m = a/b
v = a/b^2
v = m/b
b = mean/variance
a = m*b
a = mean^2/variance

```{r}
sample_mean = sample_mean - 72
sample_var = sample_var - 1/(1/72)^2
# shape = 50 # number of compartments
shape = sample_mean^2 / sample_var
# rate = 1/2 # rate = 1 / mean time spent in each compartment
rate = sample_mean / sample_var


time = seq(0, 365*2, length.out=1000)
tibble(time=time,
       density = dgamma(time, round(shape), 1/(round(1/rate)))) %>%
  ggplot(aes(x=time, y=density)) +
  geom_line()

# n = 1000
# samples = tibble(t1 = rgamma(n, shape, rate),
#                  t2 = rexp(n, 1/10),
#                  t = t1 + t2)
# ggplot(samples, aes(x=t)) +
#   geom_density()
```

Erlang dormancy with an exponential final relapse period

```{r}
d = 162
dormancy_sd = 49
dormancy_var = dormancy_sd^2

n_compartments = 11
dist_exp = list(lambda=1/72, mean = 72, var=72^2)



n = 100000
samples = tibble(i = seq_len(n),
                 Dormancy = rgamma(n, shape=d^2/dormancy_var, rate=d/dormancy_var),
                 Latency = rexp(n, rate=dist_exp$lambda),
                 `Dormancy + latency` = Dormancy + Latency) %>%
  pivot_longer(-i) %>%
  mutate(name = fct_inorder(name))

samples %>%
  group_by(name) %>%
  summarise(mean = mean(value),
            sd = sd(value))

quantile(samples$value[samples$name == "Dormancy + latency"], c(0.25, 0.75))
mean(samples$value[samples$name == "Dormancy + latency"])
sd(samples$value[samples$name == "Dormancy + latency"])

library(bayesmeta)
total_dist = convolve(function(x) {
  dgamma(x, shape=d^2/dormancy_var, rate=d/dormancy_var)
},
function(x) {
  dexp(x, rate=dist_exp$lambda)
},
delta = 0.000001,
epsilon = 0.0001)
analytic = tibble(
  tt = seq(400),
  Dormancy = dgamma(tt, shape=d^2/dormancy_var, rate=d/dormancy_var),
  Latency = dexp(tt, rate=dist_exp$lambda),
  `Dormancy + latency` = total_dist$density(tt)
) %>%
  pivot_longer(-tt) %>%
  mutate(name = fct_inorder(name))

samples %>%
  ggplot(aes(x = value, fill = name)) +
  geom_density(alpha=0.8, color="transparent") +
  facet_wrap(vars(name), ncol=1) +
  coord_cartesian(xlim=c(0, 365)) +
  labs(x = "Days", y = "Probability density") +
  theme(legend.position = "none")

analytic %>%
  ggplot(aes(x = tt/365.25*12, y = value, fill = name)) +
  geom_area(alpha=0.8, color="transparent") +
  facet_wrap(vars(name), ncol=1) +
  coord_cartesian(xlim=c(0, 12)) +
  scale_x_continuous(breaks = c(0:12)) +
  labs(x = "Months", y = "Probability density") +
  theme(legend.position = "none")

ggsave("../plots/analytic_relapse_duration.png", width=8, height=4)
```
